export const productList = [
    {
        id: 1,
        name: "Product#1",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 700,
        discountPrice: 600,
        status: true,
    },
    {
        id: 2,
        name: "Product#2",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 800,
        discountPrice: 700,
        status: true,
    },
    {
        id: 3,
        name: "Product#3",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 900,
        discountPrice: 800,
        status: true,
    },
    {
        id: 4,
        name: "Product#4",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 200,
        discountPrice: null,
        status: true,
    },
    {
        id: 5,
        name: "Product#5",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 300,
        discountPrice: null,
        status: true,
    },
    {
        id: 6,
        name: "Product#6",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 400,
        discountPrice: null,
        status: true,
    },
    {
        id: 7,
        name: "Product#7",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 500,
        discountPrice: 400,
        status: true,
    },
    {
        id: 8,
        name: "Product#8",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 100,
        discountPrice: null,
        status: true,
    },
    {
        id: 9,
        name: "Product#9",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 1100,
        discountPrice: 1000,
        status: true,
    },
    {
        id: 10,
        name: "Product#10",
        detial: "A suite of React components, sensible UI design, and a friendly development experience.",
        image: "https://via.placeholder.com/240x240",
        price: 990,
        discountPrice: 900,
        status: true,
    },
];